# Generated by Django 6.0.3 on 2026-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_office_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='half_day_after',
            field=models.TimeField(default='12:00', help_text='If employee checks in after this time, automatically marked Half Day.'),
        ),
        migrations.AddField(
            model_name='office',
            name='late_grace_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes after work_start before employee is marked Late. e.g. 15 means 09:01-09:15 = Late.'),
        ),
        migrations.AddField(
            model_name='office',
            name='work_end',
            field=models.TimeField(default='17:00', help_text='Office closing time. e.g. 17:00. Used as default check-out if employee forgets.'),
        ),
        migrations.AddField(
            model_name='office',
            name='work_start',
            field=models.TimeField(default='09:00', help_text='Office opening time. e.g. 09:00'),
        ),
    ]
