# Generated by Django 6.0.3 on 2026-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_office_half_day_after_office_late_grace_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=1, default=4.0, help_text='How many hours count as a Half Day. e.g. 4.0 means half day = 4 hours work.', max_digits=4),
        ),
    ]
