# Generated by Django 6.0.3 on 2026-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_office_half_day_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='half_day_after',
        ),
        migrations.RemoveField(
            model_name='office',
            name='half_day_hours',
        ),
        migrations.AddField(
            model_name='office',
            name='half_day_end',
            field=models.TimeField(default='15:00', help_text='Half day window end. Check-in after this time = Absent (too late even for half day).'),
        ),
        migrations.AddField(
            model_name='office',
            name='half_day_start',
            field=models.TimeField(default='12:00', help_text='Half day window start. Check-in at or after this time = Half Day.'),
        ),
    ]
